packages: []
catalogs:
  build:
    tsdown: ^0.14.1
  cli:
    '@vscode/vsce': ^3.6.0
    bumpp: ^10.2.3
    ovsx: ^0.10.5
    pncat: ^0.5.0
    taze: ^19.1.1
  dev:
    typescript: ^5.9.2
  lint:
    '@antfu/eslint-config': ^5.2.1
    eslint: ^9.33.0
    lint-staged: ^16.1.5
    simple-git-hooks: ^2.13.1
  test:
    vitest: ^3.2.4
  types:
    '@types/node': ^24.3.0
  vscode:
    reactive-vscode: ^0.3.1
    vscode-ext-gen: ^1.1.0
